navsat_transform:
  ros__parameters:
    use_sim_time: true
    frequency: 10.0
    delay: 1.0
    magnetic_declination_radians: 0.0872665  # For lat/long of Atlanta, Georgia
    yaw_offset: 0.0  # if IMU reads 0 when facing magnetic north instead of east then set parameter to pi/2
    zero_altitude:                           true
    broadcast_utm_transform:                 true
    broadcast_utm_transform_as_parent_frame: true
    publish_filtered_gps:                    false
    use_odometry_yaw:                        false
    wait_for_datum:                          false